server:
    port: 8080
spring:
    application:
        name: Docker-Demo
    datasource:
        driver-class-name: org.postgresql.Driver
        password: Aa@123
#        db_postgresql: ten name_container db
        url: jdbc:postgresql://db_postgresql:5432/postgres
#        url: jdbc:postgresql://localhost:5432/postgres
        username: root
    jpa:
        hibernate:
            ddl-auto: create
        database: postgresql
        properties:
            hibernate:
                format_sql: true
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
